# Define a build environment for the build
env=Environment(
  LIBS='reactor', #Link to this library
  CPPPATH=['#reactor','#reactor/src'], #Search here for include files,
  LIBPATH=['#build/src']) #Search here for libraries

SConscript(['src/SConscript','test/SConscript'],'env')

# Declare a main program, in the environment defined above
reactor=env.Program('reactor.cpp')
